/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2.dessin;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author tomromano
 */
public class RubberBandingDrawing extends javax.swing.JPanel {
    
    private enum STATE{
        NOT_DRAWING,DRAWING
    }

    private STATE etat;
    private int x0=0,y0=0,x1=0,y1=0;
    /**
     * Creates new form RubberBandingDrawing
     */
    public RubberBandingDrawing() {
        initComponents();
        initStateMachine();
    }
    
    private void initStateMachine(){
        etat=STATE.NOT_DRAWING;
    }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        switch(etat){
            case NOT_DRAWING:
                g.setColor(Color.black);
                g.drawLine(x0, y0, x1, y1);
                break;
            case DRAWING:
                g.setColor(Color.red);
                g.drawLine(x0, y0, x1, y1);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        switch(etat){
            case NOT_DRAWING:
                //INTERDIT
                break;
            case DRAWING:
                etat=STATE.DRAWING;
                x1=evt.getX();
                y1=evt.getY();
                repaint();
                break;
               
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        switch(etat){
            case NOT_DRAWING:
                etat=STATE.DRAWING;
                x0=evt.getX();
                y0=evt.getY();
                x1=evt.getX();
                y1=evt.getY();
                repaint();
                break;
            case DRAWING:
                //INTERDIT
                break;
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        switch(etat){
            case NOT_DRAWING:
                //INTERDIT
                break;
            case DRAWING:
                etat=STATE.NOT_DRAWING;
                x1=evt.getX();
                y1=evt.getY();
                repaint();
                break;
               
        }
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
