/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package compteur1;

/**
 *
 * @author ROMANO Tom
 */
public class Compteur1 extends javax.swing.JFrame {

    private enum STATE{
        E1,
        E2,
    }
    
    private STATE etat;
    private int labelText = 0;
    
    private void initStateMachine(){
        labelText = 0;
        etat=STATE.E1;
        ActivateE1();
        AfficherLabelText();
    }
    /**
     * Creates new form Compteur1
     */
    public Compteur1() {
        initComponents();
        initStateMachine();
    }
    
    public void AfficherLabelText(){
        compteur.setText(Integer.toString(labelText));
    }
    
    public void AfficherLabelPouf(){
        compteur.setText("Pouf!");
    }
    
    public void ActivateE1(){
        stopButton.setEnabled(false);
        startButton.setEnabled(true);
        plusUnButton.setEnabled(false);
    }

    public void ActivateE2(){
        stopButton.setEnabled(true);
        startButton.setEnabled(false);
        plusUnButton.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compteur = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        plusUnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compteur +1");

        compteur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compteur.setText("0");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        plusUnButton.setText("+1");
        plusUnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusUnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addComponent(stopButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(plusUnButton)
                .addContainerGap())
            .addComponent(compteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(compteur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(stopButton)
                    .addComponent(plusUnButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        switch(etat){
            case E1 -> {
                etat=STATE.E2;
                ActivateE2();
                labelText=0;
                AfficherLabelText();  
            }
            case E2 -> throw new IllegalStateException("stop/+1 pressed in state "+STATE.E1);  
        } 
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
         switch(etat){
            case E1 -> throw new IllegalStateException("start pressed in state "+STATE.E2); 
            case E2 -> {
                etat=STATE.E1;
                ActivateE1();
                labelText=0;
                AfficherLabelPouf();  
            }
            
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void plusUnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusUnButtonActionPerformed
         switch(etat){
            case E1 -> throw new IllegalStateException("start pressed in state "+STATE.E2); 
            case E2 -> {
                labelText+=1;
                if(labelText>3){
                    etat=STATE.E1;
                    ActivateE1();
                }else{
                    AfficherLabelText();
                }

            }
            
        }
    }//GEN-LAST:event_plusUnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compteur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compteur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compteur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compteur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compteur1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel compteur;
    private javax.swing.JButton plusUnButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
